name: occlusionformer-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.17
  - pytorch=1.8.0
  - torchvision=0.9.0
  - torchaudio=0.8.0
  - cudatoolkit=11.1.1
  - scikit-geometry=0.1.2
  - shapely=1.8.5
  - numpy=1.24.4
  - scipy=1.10.1
  - h5py=3.9.0
  - psutil=6.0.0
  - pip=23.1.2
  - pip:
    - opencv-python
    - pandas<2.0.0
    - matplotlib
    - easydict
    - pyyaml
    - glob2
    - tqdm
    - tensorboard

