# ------------------- General Options -------------------------

description                  : OcclusionFormer (before Dlow)
results_root_dir             : results
seed                         : 42
dataset                      : sdd
sdd_config_file_name         : config
# data_root_ethucy             : datasets/eth_ucy
# data_root_nuscenes_pred      : datasets/nuscenes_pred

# ------------------- Feature Extractor -------------------------

past_frames                   : 8
future_frames                 : 12
min_past_frames               : 8
min_future_frames             : 12

traj_scale                    : 1
motion_dim                    : 2
forecast_dim                  : 2
scene_side_length             : 80.0     # [m]
global_map_resolution         : 800      # [px]
rand_rot_scene                : true
max_train_agent               : 32
occlusion_process             : 'fully_observed'      # can be either 'fully_observed' or 'occlusion_simulation'
impute                        : false
momentary                     : false

# ------------------- Model -------------------------

model_id: agentformer
tf_model_dim: 256
tf_ff_dim: 512
tf_n_head: 8
tf_dropout: 0.1
input_type: ['position', 'velocity']
input_impute_markers: false
pred_type: 'scene_norm'
sn_out_type: 'norm'
pos_concat: false
pos_time_shift: 0       # for negative time codes, set it to 0, otherwise, set it to (T_obs - 1)
causal_attention: false

global_map_attention: false
#global_map_encoder:
#  model_id: global_map_cnn
#  normalize: false
#  dropout: 0.0
#  map_channels: 3
#  use_occlusion_map: true
#  output_dim: 256
#  layers:
#    - [conv2d, 4, 7, 3]     # [out_channels, kernel_size, stride]   (in_channels=None, padding=None, padding_mode=None, dilation=None, groups=None, bias=None)
#    - [maxpool, 2, 2]       # [kernel_size, stride]                 (padding=None, dilation=None, return_indices=None, ceil_mode=None)
#    - [conv2d, 8, 5, 2]
#    - [maxpool, 2, 2]
#    - [conv2d, 8, 3, 1]
#    - [maxpool, 2, 2]

context_encoder:
  n_layer: 2

future_decoder:
  n_layer: 2
  out_mlp_dim: [512, 256]

future_encoder:
  n_layer: 2
  out_mlp_dim: [512, 256]

# ------------------- VAE-------------------------

nz                           : 32
sample_k                     : 20
learn_prior                  : true

# ------------------- Training Parameters -------------------------

lr                           : 1.e-4
loss_cfg:
  mse:
    weight: 1.0
  kld:
    weight: 1.0
    min_clip: 2.0
  sample:
    weight: 1.0
    k: 20
#  occl_map:
#    weight: 1.0

num_epochs                    : 6
lr_fix_epochs                 : 10
lr_scheduler                  : 'step'
decay_step                    : 10
decay_gamma                   : 0.5
print_freq                    : 20
validation_freq               : 5000       # number of batches passed through the model between each save
validation_set_size           : 1250       # desired set size for the validation set
